syntax = "proto3";

message OrderRequest {
    int32 orderId = 1;
}

message OrderFilterRequest {
    string userId = 1;
    string status = 2;
}

// =====================
// RESPONSE MODELS
// =====================

message OrderItemResponse {
    int32 orderItemId = 1;
    int32 productId = 2;
    string productName = 3;
    double price = 4;
    int32 quantity = 5;
    double totalPrice = 6;
}

message OrderResponse {
    int32 orderId = 1;
    string userId = 2;        //  «¿Ã≤—“‹ customerId
    string status = 3;
    string orderDate = 4;

    repeated OrderItemResponse items = 5;
}

message OrderListResponse {
    repeated OrderResponse orders = 1;
}

// =====================
// SERVICE
// =====================

service OrderService {
    rpc GetOrder (OrderRequest) returns (OrderResponse);
    rpc GetAllOrders (OrderFilterRequest) returns (OrderListResponse);
}