// <auto-generated />
using AutoServiceCatalog.DAL.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoServiceCatalog.DAL.Migrations
{
    [DbContext(typeof(CarServiceContext))]
    [Migration("20250914120245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.PartDetail", b =>
                {
                    b.Property<int>("PartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartDetailId"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartDetailId");

                    b.HasIndex("PartId")
                        .IsUnique();

                    b.ToTable("PartDetails");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.PartSupplier", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("PartId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PartSupplier");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Part", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Category", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.PartDetail", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Part", "Part")
                        .WithOne("PartDetail")
                        .HasForeignKey("AutoServiceCatalog.DAL.Entities.PartDetail", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.PartSupplier", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Part", "Part")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServiceCatalog.DAL.Entities.Supplier", "Supplier")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Category", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Part", b =>
                {
                    b.Navigation("PartDetail")
                        .IsRequired();

                    b.Navigation("PartSuppliers");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("PartSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
