// <auto-generated />
using AutoServiceCatalog.DAL.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoServiceCatalog.DAL.Migrations
{
    [DbContext(typeof(CarServiceContext))]
    [Migration("20260328182019_ReplacePartWithService")]
    partial class ReplacePartWithService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.ServiceDetail", b =>
                {
                    b.Property<int>("ServiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceDetailId"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceDetailId");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("ServiceDetails");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.ServiceSupplier", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ServiceSupplier");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Service", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.ServiceDetail", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Service", "Service")
                        .WithOne("ServiceDetail")
                        .HasForeignKey("AutoServiceCatalog.DAL.Entities.ServiceDetail", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.ServiceSupplier", b =>
                {
                    b.HasOne("AutoServiceCatalog.DAL.Entities.Service", "Service")
                        .WithMany("ServiceSuppliers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServiceCatalog.DAL.Entities.Supplier", "Supplier")
                        .WithMany("ServiceSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Service", b =>
                {
                    b.Navigation("ServiceDetail")
                        .IsRequired();

                    b.Navigation("ServiceSuppliers");
                });

            modelBuilder.Entity("AutoServiceCatalog.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("ServiceSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
