@AutoserviceVehicle_HostAddress = http://localhost:5118
@accessToken = paste-access-token-from-login
@vehicleId = paste-id-from-create-response

GET {{AutoserviceVehicle_HostAddress}}/api/vehicles/decode/1HGCM82633A004352
Accept: application/json

###

GET {{AutoserviceVehicle_HostAddress}}/api/vehicles
Authorization: Bearer {{accessToken}}
Accept: application/json

###
POST {{AutoserviceVehicle_HostAddress}}/api/vehicles
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "vin": "WVWZZZ1KZAW000001",
  "make": "Volkswagen",
  "model": "Golf",
  "year": 2010,
  "mileageKm": 150000,
  "licensePlate": "AA1234BB",
  "color": "Сірий"
}

###
GET {{AutoserviceVehicle_HostAddress}}/api/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}

###
PUT {{AutoserviceVehicle_HostAddress}}/api/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "vin": "WVWZZZ1KZAW000001",
  "make": "Volkswagen",
  "model": "Golf",
  "year": 2010,
  "mileageKm": 151000,
  "licensePlate": "AA1234BB",
  "color": "Сірий"
}

###
DELETE {{AutoserviceVehicle_HostAddress}}/api/vehicles/{{vehicleId}}
Authorization: Bearer {{accessToken}}
